services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - ENVIRONMENT=development
      - BACKEND_API_URL=http://backend:8000
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
      - /app/__pycache__
    depends_on:
      - backend
    command: streamlit run streamlit_app/main.py --server.port 8501 --server.address 0.0.0.0 --server.headless true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8501/_stcore/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: constructionrag-network
