services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - BACKEND_API_URL=${BACKEND_API_URL}
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload --reload-delay 0.5
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build: 
      context: ./frontend
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    environment:
      - ENVIRONMENT=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    env_file:
      - frontend/.env
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: constructionrag-network
