steps:
  query_processing:
    semantic_expansion_count: 3
    enable_hyde_documents: true
    content_category_detection: true
    danish_query_variations: true
    
  retrieval:
    top_k: 5
    similarity_threshold: 0.7
    hybrid_search_weight: 0.5
    enable_metadata_filtering: true
    max_results_per_document: 3
    
  generation:
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 1000
    include_citations: true
    response_language: "danish"
    
orchestration:
  response_timeout_seconds: 30
  max_context_tokens: 8000
  fail_fast: true 